### ISSUE TITLE
Desync issue between Spotify and GlanceThing server

### ISSUE THREAD

**Issue by TechGeek01** [BluDood/GlanceThing#19]
**Describe the bug**
I've run into this bug *once* and have not seen it again since, but there was a time when I paused my music for a while. The computer connected to the Car Thing was not turned off in the mean time, but when I looked at the Car Thing, I noticed that the Car Thing thought it was still playing, past the end of the song, and the current progress was more than the song length..

**To Reproduce**
1. Play music
2. Pause music
3. Possibly see error??

**Expected behavior**
When pausing media, GlanceThing should reflect this. Alternatively, if for some reason it doesn't, it shouldn't go past the end of the song.

**Screenshots**
![2024-11-14 02 06 53](https://github.com/user-attachments/assets/aa4002eb-ec15-43a9-8ac9-e4552d876653)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro for Workstations 23H2 build 22631.4391
 - GlanceThing version: v0.0.6

**Comment by BluDood** [comment]
I think this will also be fixed by occasionally sending Spotify a request if nothing has happened for a while. Seems like the app missed the event where Spotify paused

**Comment by TechGeek01** [comment]
I did also notice that resuming on Spotify, or otherwise doing anything, didn't fix it. I believe the fix was to restart Spotify completely. Tapping on the pause/play button on the Car Thing also didn't do anything.

**Comment by PotatoFace1** [comment]
OS: MacOS 15.2 (24C101)
GlanceThing version: v0.0.6

I have a similar issue where the album art, song title, and progress bar don't update when i skip songs. The skip and pause buttons will still affect the new spotify song I'm playing, but it won't be reflected on the glancething UI

**Comment by BluDood** [comment]
This is a known issue, but I haven't been able to replicate it many times to diagnose what the issue actually is. I'm trying to make some general stability updates though, which probably could help. You could try the new 0.0.7 release for now

**Comment by TechGeek01** [comment]
Still seeing this issue after updating to 0.0.7 last night.

**Comment by BluDood** [comment]
Hmm, is there anything specific you do when the issue happens, or is it just after playing for a long time? Perhaps try checking the log file (%appdata%/glancething/glancething.log) to see if there's any Spotify errors.
No worries at all, hoping to be able to fix this quickly :) but yeah, really sucks to debug it when I can't reproduce the issue myself

**Comment by TechGeek01** [comment]
Seems like it only ever happens after playing for a while, and then pausing playback. I'll keep an eye on logs when it does happen though!

**Comment by TechGeek01** [comment]
Just had it not do the "count past the end of the song" thing, but rather when I hit play, it still thinks it's paused. Shows the old timestamp, not the current one. Switching tracks doesn't show on the interface either. Tapping play on the Car Thing does play the current song, though it increments the time as though it's still the song it displays.

That is, song A is displayed, at timestamp 0:11 for me. Playing in Spotify doesn't update the timestamp. Skipping songs doesn't either, but media controls on the Car Thing cause music to play song B, but Song A still displays, with time incrementing from the original 0:11 timestamp. In my case, 0:15 is 4 seconds of Car Thing being told to play song B. Playing media from Spotify, even after interacting with the Car Thing, doesn't update that timestamp, so the "0:15" is the stuck "0:11" timestamp, plus 4 seconds of playing things by using GlanceThing's media controls.

Using the media controls on the Car Thing caused a log message of

```
[05:21:36] INFO <Spotify>: Refreshing token...
```

but that's the only log message since `<adb>: Installed app!` from when the last time GlanceThing was launched. Closing Spotify and reopening doesn't cause GlanceThing to go to idle mode. Restarting GlanceThing by closing from the system tray (causing Car Thing to go into idle "reconnecting" mode) and relaunching GlanceThing on Windows fixes this in this case.

That doesn't always work though. For the original issue of the never ending timestamps, I usually have to restart Spotify and GlanceThing, and then unplug and replug Car Thing to get it to re-init things.

**Comment by BluDood** [comment]
The only bug I've managed to reproduce is when Spotify has been paused for a while, then GlanceThing "desyncs" with Spotify and any playback actions won't work. This is because Spotify seemingly unregisters the Spotify client as the "active" device and therefore the requests to play/pause/etc fails. Working on a fix for that.
I don't really know if that would help for your issue, since you describe that some actions still work. I'll let you know when I've implemented the fix and you can test :)

**Comment by TechGeek01** [comment]
Yeah, sounds like what PotatoFace1 and I noticed is that media controls on the CarThing touch screen still work, just that the play/pause and timer stuff has the desync. Like the visuals are messed up, but the controls are okay, which seems like the exact opposite as the bug you were able to reproduce.

**Comment by BluDood** [comment]
Oh i see, that would be an issue with the connection to Spotify being closed and not automatically reopening. I could add some logging to show when that happens so it's easier to debug.

**Comment by BluDood** [comment]
Added an automatic restart of the Spotify listener, including some logging, in dcb52acf1b2bd56b6b55933424a76363095b7cea. Will let you know when the update is ready :)

**Comment by BluDood** [comment]
[v0.0.8](https://github.com/BluDood/GlanceThing/releases/tag/v0.0.8) has been released with the fixes I mentioned, @TechGeek01 feel free to try that when you have time :)

**Comment by TechGeek01** [comment]
Looks like this has been working great so far as of today, with no stickage as of yet. I'll keep you posted if I notice anything weird!

**Comment by TechGeek01** [comment]
Had no error with the media playback showing the weird timer like I've seen before. I did, however, see it show as "nothing playing." Restarting Spotify didn't fix, nor did restarting GlanceThing. Unplugging and replugging the Car Thing seemed to sort things out.

**Comment by BluDood** [comment]
@TechGeek01 have you updated to 0.0.8-1? Spotify did a change which could break the GlanceThing app in some cases, so probably try that

**Comment by TechGeek01** [comment]
Just did, and that seems to have fixed the issue. I couldn't after restarting 0.0.8 even get the tray icon to appear, even though it was supposedly running in the background. I'll let you know if this seems to have solved the problem, or if I run into any issues again.

Unrelated, but 0.0.8 for me, on Windows at least, had green accents for the seekbar and such. Was there a significance to that color change? I see 0.0.8-1 is back to blue again.

**Comment by TechGeek01** [comment]
Okay, so 0.0.8-1 still does this exact same "perpetually running" thing I described in the original issue. Can't nail down what causes it though.

Restarting GlanceThing, Spotify, and even unplugging and replugging Car Thing doesn't make GlanceThing see anything. It's showing "nothing playing" currently.

**Comment by BluDood** [comment]
What do the logs say now? (%appdata%/glancething/glancething.log)

**Comment by BluDood** [comment]
> Just did, and that seems to have fixed the issue. I couldn't after restarting 0.0.8 even get the tray icon to appear, even though it was supposedly running in the background. I'll let you know if this seems to have solved the problem, or if I run into any issues again.

That's great. Yeah that's an issue I'm working on a fix for, the Spotify setup isn't catching any errors it received and ends up crashing the entire startup logic for GlanceThing, which includes the tray icon and any communication with the desktop app UI 🙃

> Unrelated, but 0.0.8 for me, on Windows at least, had green accents for the seekbar and such. Was there a significance to that color change? I see 0.0.8-1 is back to blue again.

I haven't made any changes in that regard, I don't know why yours would suddenly change

**Comment by TechGeek01** [comment]
Yeah, no idea. 0.0.8 was just ... bright green instead of blue for the loading circle, idle animation, and progress bars. ¯\_(ツ)_/¯

**Comment by BluDood** [comment]
Weird, I haven't made any changes to the colors, must be a bug with the browser or something? Anyways, are you still experiencing the issue with Spotify events? If so, please update to v0.0.8-2, reproduce the issue, and send the relevant logs here.

**Comment by TechGeek01** [comment]
I haven't seen the issue crop up in the last couple days or so, but I will update to 0.0.8-2, and let you know if I do!

**Comment by BluDood** [comment]
Alright, nice! I'll close this issue for now, feel free to reopen if you have any further issues :)

**Comment by TechGeek01** [comment]
Well guess what just happened again? This same issue!

Logs indicate
```
[22:31:30] ERROR <CarThingState>: Got an error while finding CarThing: Command failed: "C:\Users\Andy\AppData\Roaming\glancething\platform-tools\adb.exe" -s [redacted] shell ls /usr/share/qt-superbird-app/webapp/
ls: /usr/share/qt-superbird-app/webapp/: No such file or directory

[23:18:52] INFO <adb>: Found CarThing: [redacted]
[23:18:52] INFO <Client Webapp>: Downloading...
[23:18:54] INFO <Client Webapp>: Downloaded!
[23:18:55] INFO <adb>: Installing app...
[23:18:57] INFO <adb>: Installed app!
[23:19:04] INFO <Spotify>: Refreshing token...
[23:19:04] INFO <Spotify>: Refreshing token...
[23:19:04] INFO <Spotify>: Refreshing token...
[23:36:18] INFO <Spotify>: Connection closed, attempting to reopen after 5 seconds...
[23:36:27] INFO <Spotify>: Connection opened
```

This reconnect is preceeded by a shitload of the "got an error while finding CarThing" messages that repeat every 7 or 8 seconds. Time continues to tick up, even while media is paused, and the CarThing shows a previous song playing, not the current one, while the play head indicates more time than the length of the song, and continues to tick upwards (53 minutes and change at the time of writing).
