### ISSUE TITLE
JavaScript Error in Main Process – WebSocket is not open

### ISSUE THREAD

**Issue by alnavasa** [BluDood/GlanceThing#52]
**Describe the bug**
Upon opening the MacBook Pro lid in a new location (where no CarThing device is connected), the app immediately throws a persistent JavaScript error. The message indicates that a WebSocket is not open (`readyState 0 (CONNECTING)`) and attempts to send data. While the error may not be critical, the modal dialog is persistent and difficult to dismiss — it required a forced app closure.

**To Reproduce**
1. Close the MacBook Pro while GlanceThing is running.
2. Move to a different physical location where no CarThing is present.
3. Open the MacBook lid to wake the system.
4. Observe the error popup.

**Expected behavior**
The app should gracefully detect the missing WebSocket connection and avoid trying to send data until the connection is fully established. It should also fail silently or show a non-blocking message rather than an unclosable modal.

**Screenshots**
<img width="496" alt="Image" src="https://github.com/user-attachments/assets/cb8b0e24-d634-4df2-a6d9-47f6965e55c2" />

**Desktop (please complete the following information):**
 - OS: macOS (MacBook Pro, Apple Silicon)
 - GlanceThing version: Latest available at time of writing (installed from [official source/github/etc.])

**Additional context**
- The error window was persistent and could not be dismissed using regular UI.
- The only workaround was to force quit the application.
- A condition like `if (socket.readyState === WebSocket.OPEN)` before sending data could prevent this crash.

**Error Message**

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: WebSocket is not open: readyState 0 (CONNECTING)
at WebSocket.send (/Applications/GlanceThing.app/Contents/Resources/app.asar/node_modules/ws/lib/websocket.js:450:13)
at ping2 (/Applications/GlanceThing.app/Contents/Resources/app.asar/out/main/index.js:553:33)
at WebSocket. (/Applications/GlanceThing.app/Contents/Resources/app.asar/out/main/index.js:555:7)
at WebSocket.emit (node:events:518:28)
at WebSocket.setSocket (/Applications/GlanceThing.app/Contents/Resources/app.asar/node_modules/ws/lib/websocket.js:251:10)
at ClientRequest. (/Applications/GlanceThing.app/Contents/Resources/app.asar/node_modules/ws/lib/websocket.js:1012:15)
at ClientRequest.emit (node:events:518:28)
at TLSSocket.socketOnData (node:_http_client:598:11)
at TLSSocket.emit (node:events:518:28)
at addChunk (node:internal/streams/readable:561:12)
```

**Comment by BluDood** [comment]
This is probably an issue with how macOS handles sleep mode, queueing up requests until the server is available again, which fail since the carthing is unplugged. Should be fixed with some extra checks like you mentioned, I have a Mac which I could test this further on.

**Comment by alnavasa** [comment]
Still happening on latest version, but, this one time only one error popped and the app froze 

<img width="444" alt="Image" src="https://github.com/user-attachments/assets/bc2cecbc-9f95-4f99-bf40-3dba3650a725" />
<img width="481" alt="Image" src="https://github.com/user-attachments/assets/32073772-74fe-4a0c-bc89-2efa1a3f45b9" />
